eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
